name: ğŸš€ Auto Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest
    if: startsWith(github.event.head_commit.message , 'chore(release):')

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # å‘å¸ƒå¼€å§‹é€šçŸ¥
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: Release start notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          secret: ${{ secrets.DING_TALK_SECRET }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "ğŸš‘ å¼€å§‹è‡ªåŠ¨å‘å¸ƒ ğŸš‘",
                "text": "ğŸ”— è¯·ç‚¹å‡»é“¾æ¥æŸ¥çœ‹è¯¦æƒ…",
                "messageUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*gt5-RZDjt3IAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

      - name: Install dependencies
        run: yarn

      # - name: ci
      #   run: npm run ci

      - name: Prepare
        # https://github.com/lerna/lerna/issues/2404
        # https://github.com/lerna/lerna/issues/2788
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm run release

      - id: summary
        name: summary
        run: |
          JSON=$(cat ./lerna-publish-summary.json)
          echo "summary_JSON=$JSON" >> $GITHUB_OUTPUT

      # å‘å¸ƒå¤±è´¥é€šçŸ¥å†…éƒ¨å¼€å‘ç¾¤
      - name: Release failed notify
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          secret: ${{ secrets.DING_TALK_SECRET }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "ğŸ˜³ğŸ˜³ğŸ˜³ å‘å¸ƒå¤±è´¥",
                "text": "ğŸ”— è¯·ç‚¹å‡»é“¾æ¥æŸ¥çœ‹å…·ä½“åŸå› , åŠæ—¶ä¿®å¤, å°è¯•ç‚¹å‡»å³ä¸Šè§’ [Re-run all jobs] é‡è¯•, æˆ–æ‰‹åŠ¨å‘å¸ƒ ğŸš‘",
                "messageUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*PRSkSqsE_vYAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

        # å‘å¸ƒæˆåŠŸé€šçŸ¥å†…éƒ¨å¼€å‘ç¾¤
      - name: Release success notify
        if: ${{ success() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          secret: ${{ secrets.DING_TALK_SECRET }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "ğŸ‘ğŸ‘ğŸ‘ å‘å¸ƒæˆåŠŸ",
                "text": ${{ steps.summary.outputs.summary_JSON }},
                "messageUrl": "https://github.com/antvis/FEngine/releases",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*PRSkSqsE_vYAAAAAAAAAAAAADmJ7AQ/original"
              }
            }
